spring:
  application:
    name: micro-demo
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        type: trace
        use_sql_comments: true
        batch_size: 50
  aop:
    proxy-target-class: true
dubbo:
  protocol:
    port: 8000
    restport: 10000
logging:
  file: /logs
  config:
    classpath: logback-springboot.xml
  level:
    root: INFO
    org:
      hibernate:
        type: trace
