spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        type: trace
        use_sql_comments: true
        batch_size: 50
  aop:
    proxy-target-class: true
logging:
  file: /logs
  config:
    classpath: logback-springboot.xml
  level:
    root: INFO
    org:
      hibernate:
        type: trace
